Victor
AdrianRoger/OrderUp pull request #10
Opened 2024-04-20 22:28 UTC by RukimichimoshiP

Update class DinningTable and Device.
Create the HttpResponse and Exception

2024-04-21 16:06 UTC, csarfau approved these changes

2024-04-22 01:42 UTC, AdrianRoger requested changes
Your code need some changes, we are waiting for you in the next meeting.
- design pattern
- comments non deleted
- file "doc.txt" submited for pull request

2024-04-22 01:43 UTC, csarfau requested changes
See the comment above ⬆️

2024-04-23 16:56 UTC, murilornetto approved these changes

2024-04-23 23:27 UTC, AdrianRoger approved these changes

2024-04-23 23:30 UTC, csarfau approved these changes

2024-04-24 13:28 UTC, merged